[package]
name = "di-analyser"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.34"
csv = "1.3.1"
rand = "0.9.0"
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"
statrs = "0.18.0"
struct_iterable = "0.1.1"
structmap-derive = "0.1.6"
