pub static WEIGHTING_FULL: i8 = 2;
pub static WEIGHTING_PARTIAL: i8 = 1;
pub static WEIGHTING_FULL_NEG: i8 = -2;
pub static WEIGHTING_PARTIAL_NEG: i8 = -1;
pub static WEIGHTING_NOT_APPLICABLE: i8 = 0;

pub static COMPARABLE_RHO_MULTIPLIER: f64 = 5f64;
pub static ROUND_DECIMAL_PLACES_MULTIPLIER: u64 = u64::pow(10, ROUND_DEMICAL_PLACES);

static ROUND_DEMICAL_PLACES: u32 = 5;
